### ISSUE TITLE
Change rARPACK to RSpectra

### ISSUE THREAD

**Issue by yixuan** [khliland/MatrixCorrelation#1]
Hi @khliland , recently I've updated `rARPACK` to make it a simple wrapper of the [RSpectra](https://cran.r-project.org/web/packages/RSpectra/index.html) package, in order to avoid the name confusion (`rARPACK` no longer relies on ARPACK).

Would you also change the dependence on `rARPACK` to `RSpectra` in the future? All the function interfaces are unchanged, so you only need to do some name substitutions. Thanks!

**Comment by khliland** [comment]
Hi @yixuan. I will change the dependencies to follow your suggestion.
Best regards, Kristian

**Comment by yixuan** [comment]
Thanks!
